
auth.token=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

defaults.org=elevay
defaults.project=elevay

defaults.url=https://sentry.io/
